### PR TITLE
Implement starts_with, ends_with operators for Bytes

### PR DESCRIPTION
**Pull request by amiremohamadi**

### CODE REVIEW

**Comment by amiremohamadi** [comment]
Ping @marmeladema. Sorry for bothering, just wanted to know is this repo still under development?
And is there a chance that this PR will be merged?

**Comment by veeshi** [comment]
Not part of the project but for our project we implemented startswith and endswith as functions instead of operators as it is more flexible approach.

**Comment by RReverser** [comment]
Yeah this kind of use-cases is exactly what functions are for, as it doesn't require any special syntax.

**Comment by amiremohamadi** [comment]
Right, but why we have `contains` as an operator?

**Comment by RReverser** [comment]
Because Wireshark has it and this library was designed to support same syntax: https://www.wireshark.org/docs/wsug_html_chunked/ChWorkBuildDisplayFilterSection.html

If it wasn't for that, it could've been just a function too, yeah.

**Pull request closed without merging**
